(()=>{const $=s=>document.querySelector(s),cp=o=>JSON.parse(JSON.stringify(o));
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
let list=cp(products),imgs=["","","",""],editing=null;
const T=m=>{const t=document.createElement("div");t.className="toast";t.textContent=m;$("#toasts").append(t);setTimeout(()=>t.remove(),2900)};
const ok=()=>sessionStorage.getItem("tsr_admin")==="1";
function gate(){$("#lf").hidden=ok();$("#panel").hidden=!ok();if(ok())draw()}
$("#lf").onsubmit=e=>{e.preventDefault();if($("#pw").value===SITE_CONFIG.adminPassword){sessionStorage.setItem("tsr_admin","1");gate()}else T("Wrong password")};
$("#lo").onclick=()=>{sessionStorage.removeItem("tsr_admin");gate()};
const save=()=>{try{localStorage.setItem("tsr_products",JSON.stringify(list));return true}catch(e){T("Browser storage is full. Use image paths instead of uploads.");return false}};
const nextId=()=>"TSR"+String(Math.max(0,...list.map(p=>+p.id.replace(/\D/g,"")||0))+1).padStart(3,"0");
function draw(){const q=$("#aq").value.toLowerCase();$("#rows").innerHTML=list.filter(p=>!q||(p.name+p.id+p.category).toLowerCase().includes(q)).map(p=>`<tr><td><img class="thumb" src="${esc(p.images[0])}" alt=""></td><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${esc(p.category)} / ${esc(p.gender)}</td><td>₹${p.price}</td><td>${p.stock?"Yes":"No"}</td><td><button class="btn sm ghost" data-e="${esc(p.id)}">Edit</button> <button class="btn sm ghost" data-d="${esc(p.id)}">Delete</button></td></tr>`).join("");$("#cnt").textContent="("+list.length+")"}
$("#aq").oninput=draw;
const normUrl=u=>{u=u.trim();const m=u.match(/drive\.google\.com\/file\/d\/([\w-]+)/)||u.match(/drive\.google\.com\/(?:open|uc)\?(?:.*&)?id=([\w-]+)/);if(m)return "https://drive.google.com/thumbnail?id="+m[1]+"&sz=w1000";if(/dropbox\.com/.test(u))return u.replace("www.dropbox.com","dl.dropboxusercontent.com").replace(/[?&]dl=0/,"");return u};
function pv(){[0,1,2,3].forEach(i=>{const im=$("#pv"+(i+1)),st=$("#st"+(i+1));im.hidden=!imgs[i];st.textContent="";if(imgs[i]){im.onload=()=>{st.textContent="Image loaded ✓"};im.onerror=()=>{st.textContent="This link does not load as an image. Copy the image address itself (usually ends in .jpg, .png or .webp)."};im.src=imgs[i]}})}
function fill(p){editing=p?p.id:null;$("#ft").textContent=p?"Edit "+p.id:"Add product";p=p||{name:"",category:"Sneakers",gender:"Men",price:"",originalPrice:"",rating:4.5,reviewCount:0,sizes:[6,7,8,9,10],colors:["Black"],description:"",features:[],stock:true,isNew:false,isBest:false,images:["",""]};
$("#f-name").value=p.name;$("#f-cat").value=p.category;$("#f-gender").value=p.gender;$("#f-stock").value=p.stock?"1":"0";$("#f-price").value=p.price;$("#f-orig").value=p.originalPrice;$("#f-rating").value=p.rating;$("#f-rc").value=p.reviewCount;$("#f-sizes").value=p.sizes.join(",");$("#f-colors").value=p.colors.join(",");$("#f-desc").value=p.description;$("#f-feat").value=p.features.join("\n");$("#f-new").checked=!!p.isNew;$("#f-best").checked=!!p.isBest;
imgs=[0,1,2,3].map(i=>p.images[i]||"");[0,1,2,3].forEach(i=>{$("#f-i"+(i+1)).value=imgs[i].startsWith("data:")?"[image]":imgs[i];$("#u"+(i+1)).value=""});pv()}
$("#cl").onclick=()=>fill();
[1,2,3,4].forEach(n=>{$("#f-i"+n).oninput=e=>{imgs[n-1]=normUrl(e.target.value);pv()};$("#u"+n).onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const s=Math.min(1,800/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=im.width*s;c.height=im.height*s;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.drawImage(im,0,0,c.width,c.height);imgs[n-1]=c.toDataURL("image/jpeg",.82);$("#f-i"+n).value="[image]";pv()};im.src=r.result};r.readAsDataURL(f)}});
$("#pf").onsubmit=e=>{e.preventDefault();const id=editing||nextId(),cl=s=>$(s).value.split(",").map(x=>x.trim()).filter(Boolean),price=+$("#f-price").value;let orig=+$("#f-orig").value||price;if(orig<price)orig=price;
let ims;const colors=cl("#f-colors"),sizes=cl("#f-sizes").map(Number).filter(Boolean),art=shoeArt("","#ece8e1",0,$("#f-name").value.trim());ims=imgs.filter(Boolean);if(!ims.length)ims=[art];
const p={id,name:$("#f-name").value.trim(),category:$("#f-cat").value,gender:$("#f-gender").value,price,originalPrice:orig,discount:Math.round(100-price/orig*100),rating:+$("#f-rating").value||4.5,reviewCount:+$("#f-rc").value||0,images:ims,sizes:sizes.length?sizes:[6,7,8,9,10],colors:colors.length?colors:["Black"],description:$("#f-desc").value.trim(),features:$("#f-feat").value.split("\n").map(x=>x.trim()).filter(Boolean),stock:$("#f-stock").value==="1",sku:id,isNew:$("#f-new").checked,isBest:$("#f-best").checked};
const i=list.findIndex(x=>x.id===id);const old=cp(list);i>=0?list[i]=p:list.unshift(p);if(!save()){list=old;return}draw();T(i>=0?"Product updated":"Product added: "+id);fill()};
$("#rows").onclick=e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.e){fill(list.find(p=>p.id===b.dataset.e));scrollTo({top:0,behavior:"smooth"})}else if(b.dataset.d&&confirm("Delete "+b.dataset.d+"?")){list=list.filter(p=>p.id!==b.dataset.d);save();draw();T("Product deleted")}};
const dl=(n,t,m)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type:m}));a.download=n;a.click()};
$("#ex").onclick=()=>dl("products-data.js","// Generated by admin.html. Replace js/products-data.js with this file, then re-upload your site.\nconst PRODUCTS_DATA="+JSON.stringify(list,null,1)+";\n","text/javascript");
$("#exj").onclick=()=>dl("products-backup.json",JSON.stringify(list,null,1),"application/json");
$("#imp").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d)||!d.every(p=>p.id&&p.name&&p.price&&p.images))throw 0;list=d;save();draw();T("Imported "+d.length+" products")}catch(x){T("Invalid products file")}};r.readAsText(f)};
$("#rs").onclick=()=>{if(confirm("Remove saved changes from this browser and use the default list?")){localStorage.removeItem("tsr_products");location.reload()}};
fill();gate()})();