const Cart={key:"cart",items:()=>store.get(Cart.key,[]),count:()=>Cart.items().reduce((a,i)=>a+i.q,0),
save(l){store.set(Cart.key,l);updateCounts();Cart.render()},
add(id,size,color,q=1){const p=byId(id);if(!p||!p.stock)return toast("Sorry, this item is out of stock");size=size||p.sizes[0];color=color||p.colors[0];const key=[id,size,color].join("|"),l=Cart.items(),i=l.find(x=>x.key===key);i?i.q+=q:l.push({key,id,size,color,q});Cart.save(l);toast("Added to cart");$("#cc").classList.remove("bump");void $("#cc").offsetWidth;$("#cc").classList.add("bump")},
remove(key){Cart.save(Cart.items().filter(i=>i.key!==key));toast("Removed from cart")},
qty(key,d){Cart.save(Cart.items().map(i=>i.key===key?{...i,q:Math.max(1,i.q+d)}:i))},
toWish(key){const i=Cart.items().find(x=>x.key===key);if(i&&!Wish.has(i.id))Wish.toggle(i.id);Cart.remove(key)},
summary(){const l=Cart.items().filter(i=>byId(i.id));const mrp=l.reduce((a,i)=>a+byId(i.id).originalPrice*i.q,0),sub=l.reduce((a,i)=>a+byId(i.id).price*i.q,0),ship=!l.length||sub>=SITE_CONFIG.freeShippingAbove?0:SITE_CONFIG.shippingFee;return{mrp,disc:mrp-sub,ship,total:sub+ship,sub}},
rows(){return Cart.items().filter(i=>byId(i.id)).map(i=>{const p=byId(i.id);return `<div class="ci"><img src="${p.images[0]}" alt="${p.name}"><div><b>${p.name}</b><small>Size ${i.size} · ${i.color}</small><span>${money(p.price)}</span><div class="q"><button data-act="qty" data-key="${i.key}" data-d="-1" aria-label="Decrease quantity">−</button><span>${i.q}</span><button data-act="qty" data-key="${i.key}" data-d="1" aria-label="Increase quantity">+</button></div><br><button data-act="rm" data-key="${i.key}">Remove</button><button data-act="mv" data-key="${i.key}">Move to wishlist</button></div></div>`}).join("")},
sumHtml(){const s=Cart.summary();return `<div><span>Subtotal (MRP)</span><span>${money(s.mrp)}</span></div><div><span>Discount</span><span>-${money(s.disc)}</span></div><div><span>Shipping</span><span>${s.ship?money(s.ship):"Free"}</span></div><div><b>Total</b><b>${money(s.total)}</b></div>`},
open(){showOv("drw")},
render(){const empty=`<p>Your cart is empty.</p><a class="btn" href="${ROOT}shop.html">Continue shopping</a>`,has=Cart.items().length,r=Cart.rows();
$("#drw").innerHTML=`<div style="display:flex;justify-content:space-between"><h2>Cart</h2><button class="ib" data-act="close" aria-label="Close cart">✕</button></div>${has?r+`<div class="sum">${Cart.sumHtml()}</div><a class="btn" href="${ROOT}checkout.html">PROCEED TO CHECKOUT</a><a class="btn ghost" href="${ROOT}cart.html">View cart</a>`:empty}`;
const cs=$("#cosum");if(cs)cs.innerHTML=has?`<h2>Order summary</h2>${r}${Cart.sumHtml()}`:empty;const cp=$("#cartPage");if(cp)cp.innerHTML=has?`<div class="cof"><div>${r}</div><aside class="sum">${Cart.sumHtml()}<a class="btn" href="${ROOT}checkout.html">PROCEED TO CHECKOUT</a><br><br><a class="btn ghost" href="${ROOT}shop.html">CONTINUE SHOPPING</a></aside></div>`:empty}};
document.addEventListener("DOMContentLoaded",Cart.render);