const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const ROOT=document.body.dataset.root||"";
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem("tsr_"+k))??d}catch(e){return d}},set:(k,v)=>{try{localStorage.setItem("tsr_"+k,JSON.stringify(v))}catch(e){}}};
const money=n=>SITE_CONFIG.currency+Number(n).toLocaleString("en-IN");
const byId=id=>products.find(p=>p.id===id);
const stars=r=>"★".repeat(Math.round(r))+"☆".repeat(5-Math.round(r));
const waLink=t=>"https://wa.me/"+SITE_CONFIG.whatsappNumber+"?text="+encodeURIComponent(t);
function toast(m){const t=document.createElement("div");t.className="toast";t.setAttribute("role","status");t.textContent=m;$("#toasts").append(t);setTimeout(()=>t.remove(),2900)}
function card(p){const u=`${ROOT}product.html?id=${p.id}`;return `<article class="card"><div class="im"><a href="${u}" aria-label="${p.name}"><img loading="lazy" src="${p.images[0]}" alt="${p.name}"><img class="i2" loading="lazy" src="${p.images[1]||p.images[0]}" alt="" aria-hidden="true"></a>${p.discount?`<span class="bd">-${p.discount}%</span>`:""}<button class="hb${Wish.has(p.id)?" on":""}" data-act="wish" data-id="${p.id}" aria-label="Toggle wishlist for ${p.name}">♥</button><div class="qa"><button data-act="quick" data-id="${p.id}">Quick view</button><button data-act="add" data-id="${p.id}"${p.stock?"":" disabled"}>${p.stock?"Add to cart":"Sold out"}</button></div></div><p class="ct">${p.category} · ${p.gender}</p><h3><a href="${u}">${p.name}</a></h3><p class="rt"><span aria-hidden="true">${stars(p.rating)}</span> ${p.rating} (${p.reviewCount})</p><p class="pr"><b>${money(p.price)}</b> <s>${money(p.originalPrice)}</s></p></article>`}
const LINKS=[["men","Men"],["women","Women"],["sneakers","Sneakers"],["sports","Sports"],["casual","Casual"],["formal","Formal"],["boots","Boots"],["sandals","Sandals"],["sale","Sale"]];
function layout(){
$("#site-header").innerHTML=`<div class="ann">Sample announcement: edit this offer text in js/main.js</div><header id="hd"><div class="nav"><button class="ib burger" data-act="menu" aria-label="Open menu" aria-expanded="false">☰</button><a class="logo" href="${ROOT}index.html"><img id="hlogo" src="${ROOT}${SITE_CONFIG.logo}" alt="" width="36" height="36"><span>${SITE_CONFIG.brandName.toUpperCase()}</span></a><ul class="menu" id="menu"><li><a href="${ROOT}index.html">Home</a></li><li><a href="${ROOT}shop.html">Shop</a></li><li class="dd"><a href="${ROOT}shop.html">Categories</a><ul>${LINKS.map(l=>`<li><a href="${ROOT}categories/${l[0]}.html">${l[1]}</a></li>`).join("")}</ul></li><li><a href="${ROOT}shop.html?flag=new">New Arrivals</a></li><li><a href="${ROOT}shop.html?flag=best">Best Sellers</a></li><li><a href="${ROOT}categories/sale.html">Sale</a></li><li><a href="${ROOT}contact.html">Contact</a></li></ul><div class="acts"><button class="ib" data-act="search" aria-label="Search">⌕</button><button class="ib hide-m" data-act="acct" aria-label="Account">☺</button><a class="ib hide-m" href="${ROOT}wishlist.html" aria-label="Wishlist">♡<b id="wc">0</b></a><button class="ib" data-act="cart" aria-label="Open cart">▣<b id="cc">0</b></button></div></div></header>`;
const f=(h,a)=>`<h3>${h}</h3><ul>${a.map(x=>`<li><a href="${ROOT}${x[0]}">${x[1]}</a></li>`).join("")}</ul>`;
$("#site-footer").innerHTML=`<footer><div class="wrap"><div class="fg"><div><h3 class="flogo"><img id="flogo" src="${ROOT}${SITE_CONFIG.logo}" alt="" width="30" height="30"> ${SITE_CONFIG.brandName.toUpperCase()}</h3><p>Premium everyday footwear for style, comfort and quality.</p><p><a href="#" aria-label="Instagram">Instagram</a> · <a href="#" aria-label="Facebook">Facebook</a> · <a href="#" aria-label="YouTube">YouTube</a></p><p><a data-wa="Hi The Shoes Rack, I need help." href="#">WhatsApp ${SITE_CONFIG.whatsappDisplay}</a></p></div><div>${f("Shop",LINKS.slice(0,7).map(l=>[`categories/${l[0]}.html`,l[1]]))}</div><div>${f("Customer care",[["contact.html","Contact"],["policies/shipping-policy.html","Shipping"],["policies/return-policy.html","Returns"],["faq.html","FAQ"],["product.html?id=TSR001#size","Size guide"]])}</div><div>${f("Legal",[["policies/privacy-policy.html","Privacy Policy"],["policies/terms.html","Terms"],["policies/return-policy.html","Refund Policy"],["policies/cancellation-policy.html","Cancellation"],["policies/cookie-policy.html","Cookie Policy"]])}<form data-news><label class="sr" for="fe">Email</label><input id="fe" type="email" required placeholder="Email"><button class="btn sm">Subscribe</button></form></div></div><p class="fb">© 2026 The Shoes Rack. All rights reserved.</p></div></footer><a class="wf" data-wa="Hi The Shoes Rack, I'd like some help." href="#">💬 <span>Chat on WhatsApp</span></a><div id="toasts" aria-live="polite"></div>`;
$("#site-footer").insertAdjacentHTML("beforeend",`<div class="ov" id="ov" data-act="close"></div><aside class="drw" id="drw" aria-label="Cart"></aside><div class="so" id="so" aria-label="Search"><button class="btn ghost sm" data-act="close">Close</button><input id="sq" type="search" placeholder="Search name, category, SKU or gender" aria-label="Search products"><div id="sr"></div></div><div class="qv" id="qv" role="dialog" aria-modal="true"></div>`);
const FALLBACK_LOGO=ROOT+"assets/logo/logo.svg";
["#hlogo","#flogo"].forEach(sel=>{const im=$(sel);if(im)im.onerror=()=>{im.onerror=null;im.src=FALLBACK_LOGO}});
let fav=$('link[rel="icon"]');if(!fav){fav=document.createElement("link");fav.rel="icon";document.head.appendChild(fav)}
fav.href=ROOT+SITE_CONFIG.logo;
$$("[data-art]").forEach(i=>{const[a,b,l]=i.dataset.art.split("|"),art=shoeArt(a,b,0,l),u=i.dataset.img;if(u){const p=ROOT+"assets/images/"+u+".jpg";FALLBACK[p]=art;i.src=p}else i.src=art});
$$("[data-cfg]").forEach(e=>e.textContent=SITE_CONFIG[e.dataset.cfg]);
$$("[data-wa]").forEach(a=>{a.href=waLink(a.dataset.wa);a.target="_blank";a.rel="noopener"});
document.body.insertAdjacentHTML("afterbegin",'<div id="prog"></div>');const pr=$("#prog");addEventListener("scroll",()=>{pr.style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`},{passive:true});
const hd=$("#hd");const on=()=>hd.classList.toggle("sm",scrollY>40);on();addEventListener("scroll",on,{passive:true});
const hi=$("#heroimg");
if(hi&&SITE_CONFIG.heroImage){hi.src=ROOT+SITE_CONFIG.heroImage;hi.onerror=()=>{hi.onerror=null;hi.src=shoeArt("","#e4dfd6",0,SITE_CONFIG.brandName)}}
if(hi&&!matchMedia("(prefers-reduced-motion:reduce)").matches)addEventListener("scroll",()=>{hi.style.transform=`translateY(${Math.min(scrollY,600)*.08}px)`},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}}),{threshold:.1});$$(".sec>h2,.wc,.cc,.rc").forEach(e=>{e.classList.add("rvl");io.observe(e)});
$$("[data-news]").forEach(f=>f.addEventListener("submit",e=>{e.preventDefault();toast("Thanks. Newsletter is a demo until connected.");f.reset()}));
$$("[data-contact]").forEach(f=>f.addEventListener("submit",e=>{e.preventDefault();toast("Demo form: connect a form service to receive messages.");f.reset()}));
const rg=$("#reviews");if(rg){const all=[...store.get("reviews",[]),...SAMPLE_REVIEWS],n=+rg.dataset.limit||99;rg.innerHTML=all.slice(0,n).map(r=>`<div class="rc"><span aria-label="${r.r} stars" style="color:var(--ac)">${stars(r.r)}</span><p>"${r.t}"</p><b>${r.n}</b><small>${r.p} · ${r.d}</small><span class="tag">${r.n.startsWith("Sample")?"Sample review (demo)":"Submitted on this device"}</span></div>`).join("")}
const rf=$("#rf");if(rf)rf.addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(rf));store.set("reviews",[{n:d.n,p:d.p,r:+d.r,t:d.t,d:new Date().toISOString().slice(0,10)},...store.get("reviews",[])]);toast("Review saved on this device");location.reload()});
}
function closeAll(){["ov","drw","so","qv"].forEach(i=>$("#"+i).classList.remove("on"));$("#menu").classList.remove("on");$("#filters")?.classList.remove("on")}
function showOv(id){$("#ov").classList.add("on");$("#"+id).classList.add("on")}
document.addEventListener("click",e=>{const b=e.target.closest("[data-act]");if(!b)return;const a=b.dataset.act,id=b.dataset.id;
if(a==="wish")Wish.toggle(id);else if(a==="add")Cart.add(id);else if(a==="quick")Quick.open(id);else if(a==="cart")Cart.open();else if(a==="search")Search.open();
else if(a==="close")closeAll();else if(a==="menu"){$("#menu").classList.add("on");$("#ov").classList.add("on")}else if(a==="filters"){$("#filters").classList.toggle("on")}
else if(a==="acct")toast("Accounts are not available in this version");
else if(a==="qty")Cart.qty(b.dataset.key,+b.dataset.d);else if(a==="rm")Cart.remove(b.dataset.key);else if(a==="mv")Cart.toWish(b.dataset.key);else if(a==="mvc")Wish.toCart(id)});
document.addEventListener("click",e=>{const b=e.target.closest("[data-rail]");if(b){const r=b.parentElement.nextElementSibling;r.scrollBy({left:b.dataset.rail*r.clientWidth*.8,behavior:"smooth"})}});
function railArrows(){$$(".rail").forEach(r=>{if(!r.previousElementSibling?.classList.contains("ra"))r.insertAdjacentHTML("beforebegin",'<div class="ra"><button class="ib" data-rail="-1" aria-label="Scroll left">←</button><button class="ib" data-rail="1" aria-label="Scroll right">→</button></div>')})}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeAll()});
function updateCounts(){$("#wc").textContent=Wish.list().length;$("#cc").textContent=Cart.count()}
document.addEventListener("DOMContentLoaded",()=>{layout();railArrows();updateCounts()});