const Quick={open(id){const p=byId(id);if(!p)return;let s=p.sizes[0],c=p.colors[0];$("#qv").innerHTML=`<img src="${p.images[0]}" alt="${p.name}"><div><button class="ib" style="float:right" data-act="close" aria-label="Close">✕</button><h2>${p.name}</h2><p class="rt">${stars(p.rating)} ${p.rating}</p><p class="big">${money(p.price)}</p><b>Size</b><div class="opt" id="qs">${p.sizes.map(z=>`<button class="${z===s?"on":""}">${z}</button>`).join("")}</div><b>Color</b><div class="opt" id="qc">${p.colors.map(x=>`<button class="${x===c?"on":""}">${x}</button>`).join("")}</div><div class="btns" style="margin-top:12px"><button class="btn" id="qa">Add to cart</button><a class="btn wa" id="qw" target="_blank" rel="noopener" href="#">WhatsApp enquiry</a></div><a class="btn ghost" style="margin-top:8px;display:inline-block" href="${ROOT}product.html?id=${id}">View full product</a></div>`;
const qw=()=>$("#qw").href=waLink(`Hi ${SITE_CONFIG.brandName}, I'm interested in:\n\nProduct: ${p.name}\nPrice: ₹${p.price}\nSize: ${s}\nColor: ${c}\n\nPlease share availability and details.`);qw();
$("#qs").onclick=e=>{if(e.target.tagName==="BUTTON"){s=+e.target.textContent;$$("#qs button").forEach(b=>b.classList.toggle("on",b===e.target));qw()}};
$("#qc").onclick=e=>{if(e.target.tagName==="BUTTON"){c=e.target.textContent;$$("#qc button").forEach(b=>b.classList.toggle("on",b===e.target));qw()}};
$("#qa").onclick=()=>{Cart.add(id,s,c);closeAll()};showOv("qv")}};
function renderProduct(){const pd=$("#pd");if(!pd)return;const id=new URLSearchParams(location.search).get("id"),p=byId(id);
if(!p){pd.innerHTML='<h1>Product not found</h1><a class="btn" href="'+ROOT+'shop.html">Continue shopping</a>';return}
document.title=p.name+" | The Shoes Rack";let s=p.sizes[0],c=p.colors[0],q=1;
const rec=store.get("recent",[]).filter(x=>x!==id);store.set("recent",[id,...rec].slice(0,8));
const msg=()=>`Hi The Shoes Rack, I'm interested in:\n\nProduct: ${p.name}\nPrice: ₹${p.price}\nSize: ${s}\n\nPlease share availability and details.`;
const opts=(a,cur,k)=>a.map(v=>`<button data-k="${k}" class="${v===cur?"on":""}">${v}</button>`).join("");
const tabs={Description:`<p>${p.description}</p>`,Features:`<ul>${p.features.map(f=>`<li>${f}</li>`).join("")}</ul>`,"Size Guide":'<p id="size">UK/India sizes shown. [Add your size chart here.] If between sizes, choose the larger one.</p>',Shipping:"<p>[Edit shipping details.] See the shipping policy page.</p>",Returns:"<p>[Edit returns details.] See the returns policy page.</p>",Reviews:`<p>Rated ${p.rating} from ${p.reviewCount} sample ratings. <a href="${ROOT}reviews.html">See reviews</a></p>`};
pd.innerHTML=`<div class="pd"><div><div class="main" id="mi"><img id="big" src="${p.images[0]}" alt="${p.name}"></div><div class="th">${p.images.map((m,i)=>`<button class="${i?"":"on"}" data-i="${i}" aria-label="Image ${i+1}"><img src="${m}" alt=""></button>`).join("")}</div></div><div><h1>${p.name}</h1><p class="rt">${stars(p.rating)} ${p.rating} (${p.reviewCount} reviews)</p><p class="big">${money(p.price)} <s style="font-size:1rem;color:var(--gr)">${money(p.originalPrice)}</s> <span class="tag">${p.discount}% off</span></p><p>${p.stock?"In stock":"Out of stock"} · SKU ${p.sku}</p><b>Size</b><div class="opt" id="os">${opts(p.sizes,s,"s")}</div><b>Color</b><div class="opt" id="oc">${opts(p.colors,c,"c")}</div><div class="q"><button id="m" aria-label="Decrease">−</button><span id="qn">1</span><button id="pl" aria-label="Increase">+</button></div><div class="btns" style="margin-top:16px"><button class="btn" id="ac"${p.stock?"":" disabled"}>ADD TO CART</button><button class="btn ghost" id="bn"${p.stock?"":" disabled"}>BUY NOW</button><button class="btn ghost" data-act="wish" data-id="${p.id}">♥ Wishlist</button><a class="btn wa" id="wa" target="_blank" rel="noopener" href="#">WhatsApp enquiry</a></div><div class="tabs" role="tablist">${Object.keys(tabs).map((t,i)=>`<button role="tab" class="${i?"":"on"}">${t}</button>`).join("")}</div><div class="tp" id="tp">${tabs.Description}</div></div></div>`;
const wa=()=>$("#wa").href=waLink(msg());wa();
$("#os").onclick=e=>{if(e.target.dataset.k){s=+e.target.textContent;$$("#os button").forEach(b=>b.classList.toggle("on",b===e.target));wa()}};
$("#oc").onclick=e=>{if(e.target.dataset.k){c=e.target.textContent;$$("#oc button").forEach(b=>b.classList.toggle("on",b===e.target))}};
$("#m").onclick=()=>$("#qn").textContent=q=Math.max(1,q-1);$("#pl").onclick=()=>$("#qn").textContent=q=Math.min(10,q+1);
$("#ac").onclick=()=>Cart.add(p.id,s,c,q);$("#bn").onclick=()=>{store.set("buynow",[{key:[p.id,s,c].join("|"),id:p.id,size:s,color:c,q}]);location.href=ROOT+"checkout.html?buy=1"};
$(".th").onclick=e=>{const b=e.target.closest("button");if(b){$("#big").src=p.images[b.dataset.i];$$(".th button").forEach(x=>x.classList.toggle("on",x===b))}};
const mi=$("#mi");mi.onmousemove=e=>{const r=mi.getBoundingClientRect();$("#big").style.transformOrigin=`${(e.clientX-r.left)/r.width*100}% ${(e.clientY-r.top)/r.height*100}%`;$("#big").style.transform="scale(1.8)"};mi.onmouseleave=()=>$("#big").style.transform="";
$(".tabs").onclick=e=>{if(e.target.tagName==="BUTTON"){$$(".tabs button").forEach(b=>b.classList.toggle("on",b===e.target));$("#tp").innerHTML=tabs[e.target.textContent]}};
const sec=(el,t,l)=>{if(l.length)$(el).innerHTML=`<h2>${t}</h2><div class="grid">${l.slice(0,4).map(card).join("")}</div>`};
sec("#rel","Related products",products.filter(x=>x.category===p.category&&x.id!==id));
sec("#rv","Recently viewed",rec.map(byId).filter(Boolean));
$("#rv").insertAdjacentHTML("afterend",'<section class="wrap sec" id="yl"></section>');sec("#yl","You may also like",products.filter(x=>x.gender===p.gender&&x.id!==id&&x.category!==p.category))}
document.addEventListener("DOMContentLoaded",renderProduct);